In [1]:
import pandas as pd

In [2]:
url = "data/nhanes_2015_2016.csv"
da = pd.read_csv(url)

In [10]:
da.columns

Index(['SEQN', 'ALQ101', 'ALQ110', 'ALQ130', 'SMQ020', 'RIAGENDR', 'RIDAGEYR',
       'RIDRETH1', 'DMDCITZN', 'DMDEDUC2', 'DMDMARTL', 'DMDHHSIZ', 'WTINT2YR',
       'SDMVPSU', 'SDMVSTRA', 'INDFMPIR', 'BPXSY1', 'BPXDI1', 'BPXSY2',
       'BPXDI2', 'BMXWT', 'BMXHT', 'BMXBMI', 'BMXLEG', 'BMXARML', 'BMXARMC',
       'BMXWAIST', 'HIQ210'],
      dtype='str')

In [12]:
da["BMXWT"]       # we can get a mean

0        94.8
1        90.4
2        83.4
3       109.8
4        55.2
        ...
5730     59.1
5731    112.1
5732     71.7
5733     78.2
5734     58.3
Name: BMXWT, Length: 5735, dtype: float64

In [13]:
da["BMXWT"].mean()

np.float64(81.34267560889516)

In [16]:
da["DMDEDUC2"].unique()

array([ 5.,  3.,  4.,  2., nan,  1.,  9.])

In [18]:
da.columns

Index(['SEQN', 'ALQ101', 'ALQ110', 'ALQ130', 'SMQ020', 'RIAGENDR', 'RIDAGEYR',
       'RIDRETH1', 'DMDCITZN', 'DMDEDUC2', 'DMDMARTL', 'DMDHHSIZ', 'WTINT2YR',
       'SDMVPSU', 'SDMVSTRA', 'INDFMPIR', 'BPXSY1', 'BPXDI1', 'BPXSY2',
       'BPXDI2', 'BMXWT', 'BMXHT', 'BMXBMI', 'BMXLEG', 'BMXARML', 'BMXARMC',
       'BMXWAIST', 'HIQ210'],
      dtype='str')

In [20]:
g = da["RIAGENDR"]      # catagorical, unordered
g

0       1
1       1
2       1
3       2
4       2
       ..
5730    2
5731    1
5732    2
5733    1
5734    2
Name: RIAGENDR, Length: 5735, dtype: int64

In [21]:
g.unique()

array([1, 2])

In [24]:
B = ['bird', 'cat', 'dog', 'cat', 'bird', 'bird']
d = {'catagorical': B}
df = pd.DataFrame(d)

In [25]:
df

  catagorical
0        bird
1         cat
2         dog
3         cat
4        bird
5        bird

In [26]:
 df['catagorical']

0    bird
1     cat
2     dog
3     cat
4    bird
5    bird
Name: catagorical, dtype: str

In [30]:
# dummies is used to create columns corresponding to unique values
dfDummies = pd.get_dummies(df['catagorical'], prefix='catagory', dtype=int)

In [31]:
dfDummies

   catagory_bird  catagory_cat  catagory_dog
0              1             0             0
1              0             1             0
2              0             0             1
3              0             1             0
4              1             0             0
5              1             0             0

In [37]:
dfDummies.values

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1],
       [0, 1, 0],
       [1, 0, 0],
       [1, 0, 0]])